# GitHub Actions에서 수행될 동작 작성

name: Java CI with Gradle  # 작업에 대한 이름 지정

# 이벤트를 트리거하는 조건 지정
on:
  push:
    branches: [ main ]

# 하나 이상의 작업 의미
jobs:
  build:   # 작업 이름

    runs-on: ubuntu-latest   # 작업을 실행하는 머신의 운영체제

    steps:  # 작업을 수행하기 위해 실행되는 일련의 단계 정의 (name과 run으로 구성)
      - uses: actions/checkout@v2  # GitHub Actions의 마켓플레이스에 등록된 작업 실행
      - name: Set up JDK 11  # 하나의 작업 :  코드를 빌드하기 위해 JDK를 설정하고 점검
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew  # 해당 단계가 실행될 때 수행할 명령 지정
      - name: Build with Gradle  # 하나의 작업 : 코드를 gradle로 빌드
        run: ./gradlew build
      - name: Docker build  # 하나의 작업 : 빌드 완료된 JAR 파일을 run에 기입된 명령대로 수행
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t spring-cicd . 
          docker tag spring-cicd dotorii0216/spring-cicd:${GITHUB_SHA::7}
          docker push dotorii0216/spring-cicd:${GITHUB_SHA::7}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Start Session Manager session
        run: aws ssm start-session --target i-0c2e6b65fe960f4bb
      - name: Deploy to Server
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
        run: |
          aws ssm send-command \
            --instance-ids i-0c2e6b65fe960f4bb \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[
              'if sudo docker ps -a --format \\'{{.Names}}\\' | grep -q \'^server$\\'; then',
              '  sudo docker stop server',
              '  sudo docker rm server',
              'fi',
              'sudo docker pull dotorii0216/spring-cicd:${GITHUB_SHA::7}',
              'sudo docker tag dotorii0216/spring-cicd:${GITHUB_SHA::7} spring-cicd',
              'sudo docker run -d --name server -p 8080:8080 spring-cicd'
            ]" \
            --output text